name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Rustfmt
      run: cargo fmt --check

    - name: Build
      run: cargo build --release

    - name: Run tests on debug build
      run: cargo test

    - name: Run tests on release build
      run: cargo test --release

    - name: Clippy
      env:
        RUSTFLAGS: -Dwarnings
      run: cargo clippy
